### ISSUE TITLE
What is this? 

### ISSUE THREAD

**Issue by DarumasLegs** [Reelswim/coach-app-pages#1]
I saw you created this repo - what is this for?

**Comment by mifi** [comment]
It's for hosting the static fallback page for the coach app deep/universal links, e.g.:

https://coach.swimclips.com/add-video

(when coaches have not yet installed the app on their phone)

I made this repo public because that's the only way to get free github pages static site hosting, and I thought there's nothing secret here.

Alternatively we can make this repo private but then we need to pay for a github subscription ;)

**Comment by mifi** [comment]
we can also move this static site into S3 but that's more work so i didn't bother now

**Comment by DarumasLegs** [comment]
No worries - I was just wondering.

**Comment by DarumasLegs** [comment]
I tried this page, but got a broken link to the left of the Apple app store button:
<img width="264" alt="image" src="https://github.com/Reelswim/coach-app-pages/assets/19391027/8bf8168c-e4ba-442d-866c-1dbf08cbc19e">

**Comment by DarumasLegs** [comment]
Ah - that is the Play Store logo. We are only doing an iOS version to start, so you should probably remove that one...
